[package]
name = "chipsmith-quartus-common"
version = "0.1.0"
edition = "2021"

[dependencies]
chipsmith-toolchain = { path = "../chipsmith-toolchain" }
dirs = "6"
futures-util = "0.3"
reqwest = { version = "0.13", features = ["stream"] }
tokio = { version = "1", features = ["process", "fs", "io-util"] }
