[package]
name = "chipsmith-quartus-prime"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
dirs = "6"
chipsmith-toolchain = { path = "../chipsmith-toolchain" }
chipsmith-quartus-common = { path = "../chipsmith-quartus-common" }
facet = "0.46"
facet-json = "0.46"
tokio = { version = "1", features = ["process", "fs", "io-util"] }
